#!/bin/bash

# Step 1: Check if Docker is installed
if ! command -v docker &> /dev/null
then
    echo "Docker is not installed. Please install Docker first."
    exit 1
fi

# Step 2: Check if docker-compose or docker compose exists
if command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE="docker-compose"
elif docker compose version &> /dev/null; then
    DOCKER_COMPOSE="docker compose"
else
    echo "Neither docker-compose nor docker compose is installed. Please install Docker Compose."
    exit 1
fi

# Step 2.3: Make .data directory and handle permissions
mkdir -p .data/redis .data/mysql .data/postgres .data/logs/worker .data/nginx/logs

# Step 3: Start the Docker containers
$DOCKER_COMPOSE up -d

# Step 4: Run necessary installation commands
$DOCKER_COMPOSE exec app composer install

# Check if the Laravel application is running before running migrations
if $DOCKER_COMPOSE exec app php artisan migrate; then
    echo "Database migration completed."
else
    echo "Migration failed."
    exit 1
fi

# Optional: Seed the database
$DOCKER_COMPOSE exec app php artisan db:seed

# Step 5: Set permissions for the ./storage directory
cd app && chmod -R 777 ./storage

echo "Installation complete."
